version: '3.8'

services:
  
  nodeAplication:
    build:
      context: ./app-node      
    image: hugocabral28/node:prd
    container_name: nodeApp
    hostname: nodejsserver
    networks:
      - nodenet
    #tty: true

  nginx:
    build: 
      context: ./nginx
    image: hugocabral28/nginx:prd
    container_name: nginx
    hostname: nginx
    networks:
      - nodenet
    #tty: true
    ports:
      - "8080:80"
    depends_on:
      - nodeAplication

networks:
  nodenet:
    driver: bridge